-- ported to FMTK from
-- https://www.moddb.com/mods/fuel-reshaded
-- by tundrowalker
-- https://www.moddb.com/members/tundrowalker

-- Version 3.6 Experimental/Beta

-- FMTK_CURRENT_DIR only defined on startup
RESHADE_CURRENT_DIR = FMTK_CURRENT_DIR

fmtk.hook(FMTK_EVENT_ENTRY, function()
	fmtk.alias('shaders\\__setup.h', RESHADE_CURRENT_DIR .. '\\config.h')

	fmtk.alias('shaders\\base.phl', RESHADE_CURRENT_DIR .. '\\shaders\\base.phl')
	fmtk.alias('shaders\\base.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\base.vhl')
	fmtk.alias('shaders\\decal.h', RESHADE_CURRENT_DIR .. '\\shaders\\decal.h')
	fmtk.alias('shaders\\decal.phl', RESHADE_CURRENT_DIR .. '\\shaders\\decal.phl')
	fmtk.alias('shaders\\decal.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\decal.vhl')
	fmtk.alias('shaders\\flare.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\flare.vhl')
	fmtk.alias('shaders\\fx.phl', RESHADE_CURRENT_DIR .. '\\shaders\\fx.phl')
	fmtk.alias('shaders\\fx_aa.phl', RESHADE_CURRENT_DIR .. '\\shaders\\fx_aa.phl')
	fmtk.alias('shaders\\fx_blur.phl', RESHADE_CURRENT_DIR .. '\\shaders\\fx_blur.phl')
	fmtk.alias('shaders\\ground.h', RESHADE_CURRENT_DIR .. '\\shaders\\ground.h')
	fmtk.alias('shaders\\ground.phl', RESHADE_CURRENT_DIR .. '\\shaders\\ground.phl')
	fmtk.alias('shaders\\ground.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\ground.vhl')
	fmtk.alias('shaders\\ground_element.phl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_element.phl')
	fmtk.alias('shaders\\ground_element.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_element.vhl')
	fmtk.alias('shaders\\ground_gmesh.phl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_gmesh.phl')
	fmtk.alias('shaders\\ground_gmesh.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_gmesh.vhl')
	fmtk.alias('shaders\\ground_rotshape.h', RESHADE_CURRENT_DIR .. '\\shaders\\ground_rotshape.h')
	fmtk.alias('shaders\\ground_rotshape.phl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_rotshape.phl')
	fmtk.alias('shaders\\ground_rotshape.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_rotshape.vhl')
	fmtk.alias('shaders\\ground_water.h', RESHADE_CURRENT_DIR .. '\\shaders\\ground_water.h')
	fmtk.alias('shaders\\ground_water.phl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_water.phl')
	fmtk.alias('shaders\\ground_water.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\ground_water.vhl')
	fmtk.alias('shaders\\hlsl_const.h', RESHADE_CURRENT_DIR .. '\\shaders\\hlsl_const.h')
	fmtk.alias('shaders\\hlsl_math.h', RESHADE_CURRENT_DIR .. '\\shaders\\hlsl_math.h')
	fmtk.alias('shaders\\hlsl_shadow.h', RESHADE_CURRENT_DIR .. '\\shaders\\hlsl_shadow.h')
	fmtk.alias('shaders\\mesh.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\mesh.vhl')
	fmtk.alias('shaders\\mesh_shadow.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\mesh_shadow.vhl')
	fmtk.alias('shaders\\mesh_volume.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\mesh_volume.vhl')
	fmtk.alias('shaders\\omni.h', RESHADE_CURRENT_DIR .. '\\shaders\\omni.h')
	fmtk.alias('shaders\\omni.phl', RESHADE_CURRENT_DIR .. '\\shaders\\omni.phl')
	fmtk.alias('shaders\\omni.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\omni.vhl')
	fmtk.alias('shaders\\particle.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\particle.vhl')
	fmtk.alias('shaders\\rain.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\rain.vhl')
	fmtk.alias('shaders\\rotshape.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\rotshape.vhl')
	fmtk.alias('shaders\\rotshape_shadow.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\rotshape_shadow.vhl')
	fmtk.alias('shaders\\sand.h', RESHADE_CURRENT_DIR .. '\\shaders\\sand.h')
	fmtk.alias('shaders\\sand.phl', RESHADE_CURRENT_DIR .. '\\shaders\\sand.phl')
	fmtk.alias('shaders\\sand.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\sand.vhl')
	fmtk.alias('shaders\\scattering_light.h', RESHADE_CURRENT_DIR .. '\\shaders\\scattering_light.h')
	fmtk.alias('shaders\\scat_mesh.h', RESHADE_CURRENT_DIR .. '\\shaders\\scat_mesh.h')
	fmtk.alias('shaders\\scat_mesh.phl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_mesh.phl')
	fmtk.alias('shaders\\scat_mesh.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_mesh.vhl')
	fmtk.alias('shaders\\scat_part.h', RESHADE_CURRENT_DIR .. '\\shaders\\scat_part.h')
	fmtk.alias('shaders\\scat_part.phl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_part.phl')
	fmtk.alias('shaders\\scat_part.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_part.vhl')
	fmtk.alias('shaders\\scat_rotshape.h', RESHADE_CURRENT_DIR .. '\\shaders\\scat_rotshape.h')
	fmtk.alias('shaders\\scat_rotshape.phl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_rotshape.phl')
	fmtk.alias('shaders\\scat_rotshape.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_rotshape.vhl')
	fmtk.alias('shaders\\scat_skin.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\scat_skin.vhl')
	fmtk.alias('shaders\\sfx.h', RESHADE_CURRENT_DIR .. '\\shaders\\sfx.h')
	fmtk.alias('shaders\\sfx.phl', RESHADE_CURRENT_DIR .. '\\shaders\\sfx.phl')
	fmtk.alias('shaders\\sfx.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\sfx.vhl')
	fmtk.alias('shaders\\sfx2d.phl', RESHADE_CURRENT_DIR .. '\\shaders\\sfx2d.phl')
	fmtk.alias('shaders\\sfx2d.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\sfx2d.vhl')
	fmtk.alias('shaders\\shadow.phl', RESHADE_CURRENT_DIR .. '\\shaders\\shadow.phl')
	fmtk.alias('shaders\\shadow_volume.phl', RESHADE_CURRENT_DIR .. '\\shaders\\shadow_volume.phl')
	fmtk.alias('shaders\\skin.h', RESHADE_CURRENT_DIR .. '\\shaders\\skin.h')
	fmtk.alias('shaders\\skin.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\skin.vhl')
	fmtk.alias('shaders\\skin_shadow.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\skin_shadow.vhl')
	fmtk.alias('shaders\\skin_volume.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\skin_volume.vhl')
	fmtk.alias('shaders\\smoke.h', RESHADE_CURRENT_DIR .. '\\shaders\\smoke.h')
	fmtk.alias('shaders\\smoke.phl', RESHADE_CURRENT_DIR .. '\\shaders\\smoke.phl')
	fmtk.alias('shaders\\smoke.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\smoke.vhl')
	fmtk.alias('shaders\\snow.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\snow.vhl')
	fmtk.alias('shaders\\supercell.phl', RESHADE_CURRENT_DIR .. '\\shaders\\supercell.phl')
	fmtk.alias('shaders\\supercell.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\supercell.vhl')
	fmtk.alias('shaders\\tornado.h', RESHADE_CURRENT_DIR .. '\\shaders\\tornado.h')
	fmtk.alias('shaders\\tornado.phl', RESHADE_CURRENT_DIR .. '\\shaders\\tornado.phl')
	fmtk.alias('shaders\\tornado.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\tornado.vhl')
	fmtk.alias('shaders\\vizquery.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\vizquery.vhl')
	fmtk.alias('shaders\\warp.h', RESHADE_CURRENT_DIR .. '\\shaders\\warp.h')
	fmtk.alias('shaders\\warp.phl', RESHADE_CURRENT_DIR .. '\\shaders\\warp.phl')
	fmtk.alias('shaders\\warp.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\warp.vhl')
	fmtk.alias('shaders\\water.phl', RESHADE_CURRENT_DIR .. '\\shaders\\water.phl')
	fmtk.alias('shaders\\wind.vhl', RESHADE_CURRENT_DIR .. '\\shaders\\wind.vhl')
	fmtk.alias('shaders\\zonly.phl', RESHADE_CURRENT_DIR .. '\\shaders\\zonly.phl')
	fmtk.alias('shaders\\_both.h', RESHADE_CURRENT_DIR .. '\\shaders\\_both.h')
	fmtk.alias('shaders\\_pixel.h', RESHADE_CURRENT_DIR .. '\\shaders\\_pixel.h')
	fmtk.alias('shaders\\_vertex_const.h', RESHADE_CURRENT_DIR .. '\\shaders\\_vertex_const.h')
	fmtk.alias('shaders\\_vertex_scatter.h', RESHADE_CURRENT_DIR .. '\\shaders\\_vertex_scatter.h')
end)
