add_library(LuaJIT STATIC IMPORTED GLOBAL)
set_target_properties(LuaJIT PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/LuaJIT/src/luajit.lib)

add_library(LuaJIT51 STATIC IMPORTED GLOBAL)
set_target_properties(LuaJIT51 PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/LuaJIT/src/lua51.lib)

file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/LuaJIT/src/lua51.dll" DESTINATION "${CMAKE_BINARY_DIR}/bin")
