#ifndef CONFIGURE_HPP
#define CONFIGURE_HPP

#define FMTK_VERSION "0.1.0"
#define FMTK_VERSION_MAJOR 0
#define FMTK_VERSION_MINOR 1
#define FMTK_VERSION_PATCH 0
#define FMTK_VERSION_TWEAK 

#endif // CONFIGURE_HPP
