set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR X86)

set(triple i386-pc-win32-msvc)

file(TO_CMAKE_PATH "${WIDBERG_CLANG_CL}" WIDBERG_CLANG_CL)
set(CMAKE_C_COMPILER "${WIDBERG_CLANG_CL}")
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER "${WIDBERG_CLANG_CL}")
set(CMAKE_CXX_COMPILER_TARGET ${triple})

set(CMAKE_LINKER "link.exe")
set(CMAKE_AR "lib.exe")
set(CMAKE_RC "rc.exe")

# set(CMAKE_CROSSCOMPILING FALSE)
