name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        submodules: recursive
        persist-credentials: false

    - name: Resolve LLVM Nightly Installer
      id: resolve-llvm
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        "asset_name=$(gh release view nightly --repo widberg/llvm-project-widberg-extensions --json assets --jq '.assets[] | select(.name | endswith(".exe")) | .name')" >> $env:GITHUB_OUTPUT

    - name: Cache LLVM Widberg
      id: cache-llvm
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: C:\Tools\llvm-widberg
        key: llvm-widberg-${{ runner.os }}-${{ steps.resolve-llvm.outputs.asset_name }}

    - if: ${{ steps.cache-llvm.outputs.cache-hit != 'true' }}
      name: Install LLVM Widberg
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
        LLVM_ASSET_NAME: ${{ steps.resolve-llvm.outputs.asset_name }}
      run: |
        gh release download nightly --repo widberg/llvm-project-widberg-extensions --pattern "$env:LLVM_ASSET_NAME" --dir C:\TEMP --clobber
        Start-Process -FilePath "C:\TEMP\$env:LLVM_ASSET_NAME" -ArgumentList '/S','/D=C:\Tools\llvm-widberg' -Wait

    - name: Cache DXSDK
      id: cache-dxsdk
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: C:\Tools\DXSDK_Aug08
        key: dxsdk-aug08-${{ runner.os }}-1

    - if: ${{ steps.cache-dxsdk.outputs.cache-hit != 'true' }}
      name: Install DXSDK
      shell: pwsh
      run: |
        curl.exe --location --create-dirs -oC:\TEMP\DXSDK_Aug08.exe https://archive.org/download/dxsdk_aug08/DXSDK_Aug08.exe
        7z.exe x C:\TEMP\DXSDK_Aug08.exe -aoa -oC:\Tools\DXSDK_Aug08 DXSDK/Include DXSDK/Lib

    - name: Build
      shell: pwsh
      run: |
        cmd /d /s /c ('"' + (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath) + '\VC\Auxiliary\Build\vcvarsall.bat" x86 && cmake -B build -GNinja -DLLVM_WIDBERG="C:\Tools\llvm-widberg" -DDXSDK_DIR=C:\Tools\DXSDK_Aug08\DXSDK && cmake --build build')
