name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: C:\Tools
        key: tools-${{ runner.os }}-${{ hashFiles('.github\workflows\build.yml') }}

    - if: ${{ steps.cache-tools.outputs.cache-hit != 'true' }}
      name: Setup Tools
      run: |
        curl.exe --location --create-dirs -oC:\TEMP\widberg-windows-x86_64-1039ba27632b46760b87c45fc92df9dc35d5e530.zip https://nightly.link/widberg/llvm-project-widberg-extensions/workflows/widberg-build/main/widberg-windows-x86_64-1039ba27632b46760b87c45fc92df9dc35d5e530.zip
        7z.exe x C:\TEMP\widberg-windows-x86_64-1039ba27632b46760b87c45fc92df9dc35d5e530.zip -aoa -oC:\Tools\llvm-widberg
        curl.exe --location --create-dirs -oC:\TEMP\DXSDK_Aug08.exe https://archive.org/download/dxsdk_aug08/DXSDK_Aug08.exe
        7z.exe x C:\TEMP\DXSDK_Aug08.exe -aoa -oC:\Tools\DXSDK_Aug08 DXSDK/Include DXSDK/Lib

    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
      with:
        arch: x86

    - name: Build
      run: |
           cmake -B build -GNinja -DLLVM_WIDBERG="C:\Tools\llvm-widberg" -DDXSDK_DIR=C:\Tools\DXSDK_Aug08\DXSDK
           cmake --build build
