name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        arch: win32
      
    - name: Download WinFlexBison
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
    
    - name: Unzip WinFlexBison
      run: 7z x win_flex_bison-2.5.25.zip -obin
      
    - name: Download llvm-project-with-widberg-extensions
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/widberg/llvm-project-widberg-extensions/releases/download/widberg-0.0.1/widberg-0.0.1-windows-x86_64-c1243607943cc7e89a09d93e2c25711ea6d201a9.zip"
    
    - name: Unzip llvm-project-with-widberg-extensions
      run: 7z x widberg-0.0.1-windows-x86_64-c1243607943cc7e89a09d93e2c25711ea6d201a9.zip -obin

    - name: Build
      run: |
           cmake -B build -G Ninja -DWIDBERG_CLANG_CL="${{ github.workspace }}/bin/clang-cl.exe" -DBISON_EXECUTABLE="${{ github.workspace }}/bin/win_bison.exe"
           cmake --build build
