name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache
      id:   cache
      uses: actions/cache@v1
      with:
        path: ~/cache
        key:  cache

    - name: Unpack D3D
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
           curl -sSL https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe --create-dirs -o "$HOME/cache/DXSDK_Jun10.exe"
           7z x "$HOME/cache/DXSDK_Jun10.exe" DXSDK/Include "-o$HOME/cache/"
           7z x "$HOME/cache/DXSDK_Jun10.exe" DXSDK/Lib/x86 "-o$HOME/cache/"
           rm -Force "$HOME/cache/DXSDK_Jun10.exe"

    - name: Build
      run: |
           mkdir build && cd build
           cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release -DDX9SDK_DIR="$HOME/cache/DXSDK" ..
           cmake --build . --target fmtk
