name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        arch: win32
      
    - name: Download WinFlexBison
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
    
    - name: Unzip WinFlexBison
      run: 7z x win_flex_bison-2.5.25.zip -obin
      
    - name: Download llvm-project-with-widberg-extensions
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/widberg/llvm-project-widberg-extensions/releases/download/widberg-0.0.1/widberg-0.0.1-windows-x86_64-c1243607943cc7e89a09d93e2c25711ea6d201a9.zip"
    
    - name: Unzip llvm-project-with-widberg-extensions
      run: 7z x widberg-0.0.1-windows-x86_64-c1243607943cc7e89a09d93e2c25711ea6d201a9.zip -obin

    - name: Package
      run: |
           cmake -B build -G Ninja -DWIDBERG_CLANG_CL="${{ github.workspace }}/bin/clang-cl.exe" -DBISON_EXECUTABLE="${{ github.workspace }}/bin/win_bison.exe" -DCMAKE_BUILD_TYPE=Release
           cmake --build build --target package_fmtk --config Release
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        body: |
          Check the README for [installation instructions](https://github.com/widberg/fmtk#installing-for-users-and-mod-developers).
          
          Check the [documentation for users and mod developers](https://fmtk.readthedocs.io/en/latest/) to see what you can do with FMTK.
        draft: false
        prerelease: false
    
    - name: Upload FMTK Archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: fmtk-${{ github.ref_name }}-${{ github.sha }}.zip
        asset_path: build/fmtk.zip
        asset_content_type: application/zip

    - name: Upload FMTKSDK Archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: fmtksdk-${{ github.ref_name }}-${{ github.sha }}.zip
        asset_path: build/fmtksdk.zip
        asset_content_type: application/zip
