name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Package
      run: |
           mkdir build && cd build
           cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release ..
           cmake --build . --target package --config Release
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Check the README for [installation instructions](https://github.com/widberg/fmtk#installing-for-users-and-mod-developers).
          
          Check the [documentation for users and mod developers](https://fmtk.readthedocs.io/en/latest/) to see what you can do with FMTK.
        draft: false
        prerelease: false
    
    - name: Upload FMTK Archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: fmtk-${{ github.sha }}.zip
        asset_path: build/fmtk.zip
        asset_content_type: application/zip

    - name: Upload FMTKSDK Archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: fmtksdk-${{ github.sha }}.zip
        asset_path: build/fmtksdk.zip
        asset_content_type: application/zip
